version: "3.9"

services:
  backend:
    image: carservice-backend
    container_name: carservice-backend
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    image: carservice-frontend
    container_name: carservice-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
